### 1. 회원가입
POST http://localhost:8080/api/auth/join
Content-Type: application/json

{
  "loginId": "sohi",
  "password": "pw",
  "name": "이소희",
  "email": "sohe@shinhan.com",
  "phoneNumber": "010-1422-3345",
  "birthdate": "2003-11-21",
  "ciDi": "1"
}

### 2. 로그인 후 access/refresh token 저장
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "loginId": "sohi",
  "password": "pw"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

### 3. access token으로 인증
GET http://localhost:8080/api/users/me
Authorization: Bearer {{access_token}}

### 4. refresh token으로 access/refresh 재발급
POST http://localhost:8080/api/auth/reissue
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

### 5. 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}
