spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: esg-be

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
jwt:
  secret: ${JWT_SECRET} # 실제 값은 .env 파일에 넣음
  expiration: 86400000 # 토큰 만료 시간
